apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
# if not specified, an application belongs to default project
  project: default

  source:
    repoURL: https://github.com/zhangzhao1991512/ArgoCD-demo.git
    targetRevision: HEAD
    path: dev
  destination: 
  # the internal service name of kube api server (we are running argocd inside the cluster)
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true